### ISSUE TITLE
Users should only be able to view Scans that they have created

### ISSUE THREAD

**Issue by pJeyakumar** [Dhruv-Panicker/ExcelGuard#25]
Currently a user is able to see any scan that were created (meaning they'd be able to view scans created by other users). As it stands, a user should only be able to view their OWN scans (unless a scan is shared with them, which will be addressed in Issue #15)

**Comment by pJeyakumar** [comment]
@kdmaclean here is the issue regarding restricting "Previous Scans" to those that the user have created themselves

**Comment by kdmaclean** [comment]
@pJeyakumar Thanks! I think I might have to be a contributor to add a branch and such. Can you give me access?
